spring:
  application:
    name: users
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: test
    password: test
  sql:
    init:
      mode: embedded
  web:
   error:
    include-binding-errors: always
    include-message: always

logging:
  level:
    io:
      r2dbc:
        h2: DEBUG

token:
  secret: a9X3bZ7qL2mP4vR8tY6wN1jK5sH0dF3eG7uC9oM2xV4rT8yB6nJ1lQ5pW0z